version: '3'

services:
  mongo:
    image: mongo
    ports:
      - "1234:27017"
    networks:
      -  task-manager-network
  
  api:
    build:
      context: .
      dockerfile: ./TaskManager.WebApi/Dockerfile
    environment:
      MONGODB_SERVER: mongodb://mongo:27017
      MONGODB_DATABASE: TaskManager
    ports:
      - "8080:80"
    networks:
      - task-manager-network
    links:
      - mongo
    depends_on:
      - mongo

networks: 
    task-manager-network:
      driver: bridge
